name: Build Gemini Nano Android App (and upload the artifact!)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'gemini-nano/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'gemini-nano/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make gradlew executable
      working-directory: ./gemini-nano
      run: chmod +x ./gradlew

    - name: Build Gemini Nano app
      working-directory: ./gemini-nano
      run: ./gradlew :app:assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: gemini-nano/app/build/outputs/apk/debug/app-debug.apk
